# Generated by Django 5.2.9 on 2025-12-10 21:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(default='islamabad', max_length=100)),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_budget', models.DecimalField(decimal_places=2, default=10000000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_bedrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_bedrooms', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_bathrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_area_sqft', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)])),
                ('property_types', models.JSONField(blank=True, default=list)),
                ('profession', models.CharField(blank=True, default='', max_length=50)),
                ('timeline', models.CharField(blank=True, default='', max_length=50)),
                ('purpose', models.CharField(choices=[('living', 'Living'), ('investment', 'Investment'), ('rental', 'Rental')], default='living', max_length=20)),
                ('hospital_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('school_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('restaurant_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('shopping_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('park_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metro_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('security_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('parking_importance', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
    ]
