# Generated by Django 5.2.9 on 2025-12-10 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location', 'price'], name='properties_locatio_828930_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms', 'bathrooms'], name='properties_bedroom_2aae3d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'verified'], name='properties_propert_7f3039_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties_created_2ede73_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'verified'], name='properties_is_acti_258303_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyfeature',
            unique_together={('property', 'name')},
        ),
    ]
