# Generated by Django 5.2.9 on 2025-12-11 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='security_score',
            field=models.FloatField(default=0.5, help_text='Security and safety score for the area (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
