# Generated by Django 4.2.7 on 2026-02-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_add_property_detail_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='demand_level',
        ),
        migrations.RemoveField(
            model_name='property',
            name='legal_compliance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='market_appreciation_rate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='weather_risk',
        ),
    ]
