# Generated by Django 4.2.7 on 2026-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_demand_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.JSONField(blank=True, default=list, help_text="List of regulatory approvals, e.g. ['CDA', 'RDA', 'PHATA']"),
        ),
    ]
